version: 2
jobs:
  build:
    working_directory: ~/boxy
    docker:
      - image: node:8.1
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Checking Versions
          command: |
            node --version
            npm --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/boxy/node_modules
