version: 2
jobs:
  build:
    working_directory: ~/boxy
    docker:
      - image: node:8.1
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Checking Versions
          command: |
            node --version
            yarn --version
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/boxy/node_modules
